# Configuration file for conda

name: generative-playground
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
    # Development deps
    - ipython
    - isort
    - jupyter
    - jupyterlab
    - jupyterlab-spellchecker
    - llvm-openmp
    - matplotlib
    - pandas
    - pip
    - scikit-learn
    - python=3.9.*
    - tqdm

    - pip:
        - torchvision
        - torchaudio
        - torch==2.0.*
        - functorch
        # - -e .
